import type { Express } from "express";
import { db } from "./db";
import { users } from "@shared/schema";
import { eq } from "drizzle-orm";
import { getUncachableStripeClient, getStripePublishableKey } from "./stripeClient";
import { sql } from "drizzle-orm";
import { checkoutSignalLimiter } from "./rate-limit";
import { verifyCheckoutToken } from "./checkout-token";

// Accepts session cookie (web) OR a body checkoutToken (native apps where cross-origin
// cookies are unreliable). The token is a short-lived HMAC generated by /api/auth/me.
async function getUserId(req: any): Promise<number> {
  const sessionId = (req.session as any)?.userId;
  const origin = req.headers.origin ?? 'none';
  const hasCookie = !!(req.headers.cookie);

  if (sessionId) {
    console.log(`[Auth] session OK userId=${sessionId} origin=${origin}`);
    return sessionId;
  }

  const { userId: bodyUserId, checkoutToken } = req.body ?? {};
  console.log(`[Auth] no session — origin=${origin} hasCookie=${hasCookie} bodyUserId=${bodyUserId} hasToken=${!!checkoutToken} bodyKeys=${Object.keys(req.body ?? {}).join(',')}`);

  if (bodyUserId && checkoutToken) {
    const id = Number(bodyUserId);
    if (!isNaN(id) && id > 0 && verifyCheckoutToken(id, checkoutToken)) {
      const [user] = await db.select({ id: users.id }).from(users).where(eq(users.id, id));
      if (user) {
        console.log(`[Auth] token OK userId=${user.id}`);
        return user.id;
      }
    }
    console.log(`[Auth] token INVALID userId=${bodyUserId}`);
  }

  throw Object.assign(new Error("Not authenticated"), { status: 401 });
}

// ── Helpers ───────────────────────────────────────────────────────────────
const ANNUAL_AMOUNT_PENCE = 4999;  // £49.99
const MONTHLY_AMOUNT_PENCE = 599;  // £5.99

function calcAnnualRefund(periodStartMs: number): { monthsUsed: number; refundPence: number; refundFormatted: string } {
  const msUsed = Date.now() - periodStartMs;
  const monthsUsed = Math.max(1, Math.ceil(msUsed / (30 * 24 * 60 * 60 * 1000)));
  const charged = monthsUsed * MONTHLY_AMOUNT_PENCE;
  const refundPence = Math.max(0, ANNUAL_AMOUNT_PENCE - charged);
  const refundFormatted = `£${(refundPence / 100).toFixed(2)}`;
  return { monthsUsed, refundPence, refundFormatted };
}

// Returns a valid Stripe customer ID for the user in the current Stripe mode.
// If the stored ID belongs to a different mode (e.g. test vs live), it creates a fresh one.
async function getOrCreateStripeCustomer(
  stripe: import('stripe').default,
  user: { id: number; username: string; displayName: string | null; stripeCustomerId: string | null }
): Promise<string> {
  if (user.stripeCustomerId) {
    try {
      const existing = await stripe.customers.retrieve(user.stripeCustomerId);
      if (!('deleted' in existing)) return existing.id;
    } catch (e: any) {
      // "No such customer" — stale ID from wrong Stripe mode; fall through to create new
      console.warn(`[Stripe] Stale customer ID ${user.stripeCustomerId}, creating fresh one:`, e.message);
    }
  }
  const customer = await stripe.customers.create({
    email: user.username,
    name: user.displayName ?? user.username,
    metadata: { userId: String(user.id) },
  });
  await db.update(users).set({ stripeCustomerId: customer.id }).where(eq(users.id, user.id));
  console.log(`[Stripe] Created customer ${customer.id} for user ${user.id}`);
  return customer.id;
}

// ── Stripe Premium Price — singleton cache ────────────────────────────────────
let _priceIdPromise: Promise<string> | null = null;
let _annualPriceIdPromise: Promise<string> | null = null;

async function _getOrCreateProduct(): Promise<{ product: import('stripe').default.Product; keyMode: string }> {
  const stripe = await getUncachableStripeClient();
  const keyMode = (process.env.STRIPE_SECRET_KEY ?? '').startsWith('sk_live') ? 'LIVE' : 'TEST';
  const allProducts = await stripe.products.list({ active: true, limit: 100 });
  let product = allProducts.data.find(p => p.name === 'DBrief Premium');
  if (!product) {
    product = await stripe.products.create({
      name: 'DBrief Premium',
      description: 'Full access to all DBrief premium features — voice notes, squad, weekly reports, pattern analysis & mission intelligence.',
    });
    console.log(`[Stripe] Product created in ${keyMode} mode: ${product.id}`);
  }
  return { product, keyMode };
}

async function _findOrCreatePremiumPrice(): Promise<string> {
  const stripe = await getUncachableStripeClient();
  const keyMode = (process.env.STRIPE_SECRET_KEY ?? '').startsWith('sk_live') ? 'LIVE' : 'TEST';
  console.log(`[Stripe] Resolving premium price (${keyMode} mode)...`);

  const envPriceId = process.env.STRIPE_PRICE_ID;
  if (envPriceId) {
    try {
      const price = await stripe.prices.retrieve(envPriceId);
      if (price.active) { console.log(`[Stripe] Premium price from env: ${price.id}`); return price.id; }
    } catch (e: any) {
      console.warn(`[Stripe] STRIPE_PRICE_ID (${envPriceId}) not in ${keyMode} mode — will find/create.`);
    }
  }

  const { product } = await _getOrCreateProduct();
  const prices = await stripe.prices.list({ product: product.id, active: true, limit: 20 });
  const monthly = prices.data.find(p => p.recurring?.interval === 'month');
  if (monthly) { console.log(`[Stripe] Premium price ready: ${monthly.id} (${keyMode})`); return monthly.id; }

  const price = await stripe.prices.create({
    product: product.id, unit_amount: 599, currency: 'gbp', recurring: { interval: 'month' },
  });
  console.log(`[Stripe] Monthly price created: ${price.id}`);
  return price.id;
}

async function _findOrCreateAnnualPrice(): Promise<string> {
  const stripe = await getUncachableStripeClient();
  const keyMode = (process.env.STRIPE_SECRET_KEY ?? '').startsWith('sk_live') ? 'LIVE' : 'TEST';
  console.log(`[Stripe] Resolving annual price (${keyMode} mode)...`);

  const { product } = await _getOrCreateProduct();
  const prices = await stripe.prices.list({ product: product.id, active: true, limit: 20 });
  const annual = prices.data.find(p => p.recurring?.interval === 'year');
  if (annual) { console.log(`[Stripe] Annual price ready: ${annual.id} (${keyMode})`); return annual.id; }

  const price = await stripe.prices.create({
    product: product.id, unit_amount: 4999, currency: 'gbp', recurring: { interval: 'year' },
  });
  console.log(`[Stripe] Annual price created: ${price.id}`);
  return price.id;
}

/** Called once at server startup. Warms up both price caches so checkout is instant. */
export function warmupStripePremiumPrice(): void {
  if (!_priceIdPromise) {
    _priceIdPromise = _findOrCreatePremiumPrice().catch((e) => {
      console.error('[Stripe] Monthly price warmup failed:', e.message);
      _priceIdPromise = null;
      throw e;
    });
  }
  if (!_annualPriceIdPromise) {
    _annualPriceIdPromise = _findOrCreateAnnualPrice().catch((e) => {
      console.error('[Stripe] Annual price warmup failed:', e.message);
      _annualPriceIdPromise = null;
      throw e;
    });
  }
}

async function getPremiumPriceId(): Promise<string> {
  if (!_priceIdPromise) warmupStripePremiumPrice();
  return _priceIdPromise!;
}

async function getAnnualPriceId(): Promise<string> {
  if (!_annualPriceIdPromise) warmupStripePremiumPrice();
  return _annualPriceIdPromise!;
}

export function isPremiumStatus(status: string | null | undefined): boolean {
  return status === 'premium' || status === 'beta';
}

export function registerSubscriptionRoutes(app: Express) {

  // ── GET /.well-known/apple-pay-domain-association ─────────────────────────
  // Required by Apple/Stripe to enable Apple Pay on dbrief.replit.app.
  // After adding the domain in Stripe Dashboard → Settings → Apple Pay,
  // download the domain association file and set its contents in the
  // APPLE_PAY_DOMAIN_ASSOCIATION environment variable.
  app.get("/.well-known/apple-pay-domain-association", (req, res) => {
    const fileContent = process.env.APPLE_PAY_DOMAIN_ASSOCIATION;
    if (!fileContent) return res.status(404).send("Not configured");
    res.setHeader("Content-Type", "application/json");
    res.send(fileContent);
  });

  // ── GET /checkout-return ──────────────────────────────────────────────────
  // Landing page for native (iOS + Android) Stripe checkout.
  // SFSafariViewController / Chrome Custom Tab redirect here after payment so
  // users see a clean "return to app" screen instead of the full web UI.
  app.get("/checkout-return", (req, res) => {
    const result = req.query.result as string;
    const success = result === 'success';

    const sessionId = req.query.session_id as string | undefined;
    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>DBrief App</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      background: #141414; color: #f5f5f5;
      min-height: 100dvh; display: flex; flex-direction: column;
      align-items: flex-start; justify-content: flex-start;
      padding: 3.5rem 2rem 2rem;
      text-align: left; overflow: hidden;
    }
    .icon { font-size: 3rem; margin-bottom: 1rem; }
    h1 { font-size: 1.6rem; font-weight: 800; margin-bottom: 0.5rem; letter-spacing: -0.3px; }
    p { font-size: 0.95rem; color: #a3a3a3; line-height: 1.6; margin-bottom: 0.5rem; }
    .status {
      margin-top: 2.5rem;
      display: inline-flex; align-items: center; gap: 0.6rem;
      font-size: 0.9rem; color: #d97706; font-weight: 600;
    }
    .spinner {
      width: 18px; height: 18px; flex-shrink: 0;
      border: 2.5px solid #333; border-top-color: #d97706;
      border-radius: 50%;
      animation: spin 0.8s linear infinite;
    }
    .hint {
      display: none; margin-top: 1.5rem;
      background: #1f1f1f; border: 1px solid #2a2a2a;
      border-radius: 14px; padding: 1rem 1.25rem;
    }
    .hint p { color: #c4c4c4; margin: 0; font-size: 0.9rem; line-height: 1.6; }
    .hint strong { color: #f5f5f5; }
    @keyframes spin { to { transform: rotate(360deg); } }
  </style>
</head>
<body>
  <div class="icon">${success ? '🏁' : '👋'}</div>
  <h1>${success ? "You're on the grid." : 'No worries.'}</h1>
  <p>${success
    ? 'DBrief App Premium is now active. The app will detect your subscription automatically.'
    : 'Your subscription was not completed.'
  }</p>
  ${success ? `
  <div class="status" id="st">
    <div class="spinner" id="sp"></div>
    <span id="st-text">Returning you to DBrief App…</span>
  </div>
  <script>
    (async function() {
      var sid = ${sessionId ? JSON.stringify(sessionId) : 'null'};
      // 1. Signal server — marks subscription premium in DB before app polls.
      if (sid) {
        try { await fetch('/api/subscription/checkout-signal?session_id=' + encodeURIComponent(sid)); }
        catch(_) {}
      }
      // 2. Update status text.
      document.getElementById('sp').style.display = 'none';
      document.getElementById('st-text').textContent = 'Payment confirmed.';
      // 3. Attempt deep-link return. iOS will show its own "Open in DBrief?"
      //    confirmation dialog — no on-page instruction needed.
      //    If the URL scheme is not registered, the user closes this view
      //    with the native Done button in the browser toolbar.
      try {
        window.location.href = 'dbrief://checkout-done?result=${success ? 'success' : 'cancelled'}' +
          (sid ? '&session_id=' + encodeURIComponent(sid) : '');
      } catch(_) {}
    })();
  </script>
  ` : ''}
</body>
</html>`;

    res.setHeader('Content-Type', 'text/html');
    res.send(html);
  });

  // ── GET /api/subscription/status ─────────────────────────────────────────
  app.get("/api/subscription/status", async (req, res) => {
    try {
      const userId = await getUserId(req);
      const [user] = await db.select({
        subscriptionStatus: users.subscriptionStatus,
        subscriptionCurrentPeriodEnd: users.subscriptionCurrentPeriodEnd,
      }).from(users).where(eq(users.id, userId));

      const status = user?.subscriptionStatus ?? 'free';
      res.json({
        status,
        isPremium: isPremiumStatus(status),
        currentPeriodEnd: user?.subscriptionCurrentPeriodEnd ?? null,
      });
    } catch (err: any) {
      res.status(err.status || 500).json({ message: err.message });
    }
  });

  // ── GET /api/subscription/publishable-key ────────────────────────────────
  app.get("/api/subscription/publishable-key", async (_req, res) => {
    try {
      const key = await getStripePublishableKey();
      res.json({ publishableKey: key });
    } catch (err: any) {
      res.status(500).json({ message: err.message });
    }
  });

  // ── GET /api/subscription/payment-link ───────────────────────────────────
  // Returns the Stripe Payment Link URL (supports Apple Pay, Klarna, etc.)
  // for use in native iOS via SFSafariViewController (Browser plugin).
  app.get("/api/subscription/payment-link", async (_req, res) => {
    try {
      // Allow override via env var for instant config without a deploy.
      if (process.env.STRIPE_PAYMENT_LINK_URL) {
        return res.json({ url: process.env.STRIPE_PAYMENT_LINK_URL });
      }
      const stripe = await getUncachableStripeClient();
      const priceId = await getPremiumPriceId();
      // Find the active payment link that uses the premium price.
      const links = await stripe.paymentLinks.list({ active: true, limit: 20 });
      let found: string | null = null;
      for (const link of links.data) {
        const items = await stripe.paymentLinks.listLineItems(link.id, { limit: 5 });
        if (items.data.some(i => i.price?.id === priceId)) {
          found = link.url;
          break;
        }
      }
      if (!found) return res.status(404).json({ message: "No active payment link found for this plan." });
      res.json({ url: found });
    } catch (err: any) {
      res.status(500).json({ message: err.message });
    }
  });

  // ── GET /api/stripe/config ───────────────────────────────────────────────
  // Returns the Stripe publishable key for use by client-side Stripe.js.
  // The publishable key is intentionally public (it's shipped in frontend code).
  app.get("/api/stripe/config", (_req, res) => {
    const publishableKey = process.env.STRIPE_PUBLISHABLE_KEY ?? "";
    res.json({ publishableKey });
  });

  // ── POST /api/subscription/checkout-embedded ─────────────────────────────
  // Returns a Stripe Checkout clientSecret for Embedded Checkout (ui_mode='embedded').
  // The checkout form renders inside the native app — no external browser needed.
  app.post("/api/subscription/checkout-embedded", async (req, res) => {
    try {
      const userId = await getUserId(req);
      const [user] = await db.select().from(users).where(eq(users.id, userId));
      if (!user) return res.status(404).json({ message: "User not found" });

      const stripe = await getUncachableStripeClient();
      const customerId = await getOrCreateStripeCustomer(stripe, user);
      const priceId = await getPremiumPriceId();

      const host = req.headers.host ?? process.env.REPLIT_DOMAINS?.split(',')[0] ?? 'localhost:5000';
      const protocol = host.startsWith('localhost') ? 'http' : 'https';
      // Return URL navigates back into the React app — App.tsx detects ?subscription=success
      // and shows the premium toast. Stripe appends ?session_id=... automatically for
      // embedded checkout so App.tsx can immediately sync via checkout-signal.
      const returnUrl = `${protocol}://${host}/?subscription=success`;

      const session = await stripe.checkout.sessions.create({
        customer: customerId,
        payment_method_types: ['card'],
        line_items: [{ price: priceId, quantity: 1 }],
        mode: 'subscription',
        ui_mode: 'embedded',
        return_url: returnUrl,
        allow_promotion_codes: true,
      });

      res.json({ clientSecret: session.client_secret });
    } catch (err: any) {
      console.error('[Stripe] Embedded checkout error:', err.message, err.status);
      res.status(err.status || 500).json({ message: err.message });
    }
  });

  // ── POST /api/subscription/checkout ──────────────────────────────────────
  app.post("/api/subscription/checkout", async (req, res) => {
    try {
      const userId = await getUserId(req);
      const [user] = await db.select().from(users).where(eq(users.id, userId));
      if (!user) return res.status(404).json({ message: "User not found" });

      const stripe = await getUncachableStripeClient();
      const customerId = await getOrCreateStripeCustomer(stripe, user);
      const plan = req.body?.plan === 'annual' ? 'annual' : 'monthly';
      const priceId = plan === 'annual' ? await getAnnualPriceId() : await getPremiumPriceId();

      const host = req.headers.host ?? process.env.REPLIT_DOMAINS?.split(',')[0] ?? 'localhost:5000';
      const protocol = host.startsWith('localhost') ? 'http' : 'https';
      const baseUrl = `${protocol}://${host}`;

      const isNative = req.body?.native === true;
      const successUrl = isNative
        ? `${baseUrl}/checkout-return?result=success&session_id={CHECKOUT_SESSION_ID}`
        : `${baseUrl}/?subscription=success`;
      const cancelUrl = isNative
        ? `${baseUrl}/checkout-return?result=cancelled`
        : `${baseUrl}/?subscription=cancelled`;

      const session = await stripe.checkout.sessions.create({
        customer: customerId,
        payment_method_types: ['card'],
        line_items: [{ price: priceId, quantity: 1 }],
        mode: 'subscription',
        success_url: successUrl,
        cancel_url: cancelUrl,
        allow_promotion_codes: true,
      });

      res.json({ url: session.url });
    } catch (err: any) {
      console.error('[Stripe] Checkout error:', err);
      res.status(err.status || 500).json({ message: err.message });
    }
  });

  // ── GET /api/subscription/checkout-signal ────────────────────────────────
  // Called by the checkout-return page (running inside SFSafariViewController)
  // using the Stripe session ID as proof of payment — no session cookie needed.
  // Immediately syncs the subscription without waiting for the webhook.
  app.get("/api/subscription/checkout-signal", checkoutSignalLimiter, async (req, res) => {
    const sessionId = req.query.session_id as string;
    if (!sessionId) return res.status(400).json({ ok: false });
    try {
      const stripe = await getUncachableStripeClient();
      const session = await stripe.checkout.sessions.retrieve(sessionId, {
        expand: ['subscription'],
      });
      if (session.payment_status !== 'paid' || !session.customer) {
        return res.json({ ok: false, reason: 'not_paid' });
      }
      const customerId = typeof session.customer === 'string' ? session.customer : session.customer.id;
      const [user] = await db.select().from(users).where(eq(users.stripeCustomerId, customerId));
      if (!user) return res.json({ ok: false, reason: 'no_user' });
      let periodEnd: Date | null = null;
      if (session.subscription && typeof session.subscription !== 'string') {
        const sub = session.subscription as import('stripe').default.Subscription;
        if (sub.current_period_end) periodEnd = new Date(sub.current_period_end * 1000);
      }
      await db.update(users).set({
        subscriptionStatus: 'premium',
        ...(periodEnd ? { subscriptionCurrentPeriodEnd: periodEnd } : {}),
      }).where(eq(users.id, user.id));
      return res.json({ ok: true });
    } catch (err: any) {
      return res.json({ ok: false, reason: err.message });
    }
  });

  // ── POST /api/subscription/sync ──────────────────────────────────────────
  // Reads the live subscription state from Stripe and updates the DB.
  // Called on app load so missed webhooks never leave users in wrong state.
  app.post("/api/subscription/sync", async (req, res) => {
    try {
      const userId = await getUserId(req);
      const [user] = await db.select().from(users).where(eq(users.id, userId));
      if (!user?.stripeCustomerId) {
        // No Stripe customer yet — definitely free
        return res.json({ status: 'free', isPremium: false, synced: false });
      }

      const stripe = await getUncachableStripeClient();

      // Helper: resolve the most relevant status from a list of subscriptions
      function resolveStatus(subs: import('stripe').default.Subscription[], currentStatus: string): { newStatus: string; periodEnd: Date | null } {
        const active = subs.find(s => s.status === 'active' || s.status === 'trialing');
        const latest = subs[0];
        let newStatus: string;
        let periodEnd: Date | null = null;
        if (active) {
          newStatus = 'premium';
          periodEnd = active.current_period_end ? new Date(active.current_period_end * 1000) : null;
        } else if (latest && (latest.status === 'canceled' || latest.status === 'unpaid' || latest.status === 'incomplete_expired')) {
          newStatus = 'free';
        } else if (!latest) {
          newStatus = 'free';
        } else {
          newStatus = currentStatus ?? 'free';
        }
        return { newStatus, periodEnd };
      }

      // Primary lookup: by stored stripeCustomerId
      const subscriptions = await stripe.subscriptions.list({
        customer: user.stripeCustomerId,
        status: 'all',
        limit: 5,
      });

      let { newStatus, periodEnd } = resolveStatus(subscriptions.data, user.subscriptionStatus ?? 'free');
      let healedCustomerId: string | null = null;

      // If we found no active subscription via the stored customer ID, search Stripe
      // by email. This heals users who paid via a payment link (which creates an
      // anonymous customer we couldn't pre-store) or had a stale customer ID.
      if (newStatus === 'free' && user.username) {
        const customers = await stripe.customers.search({
          query: `email:"${user.username}"`,
          limit: 5,
        });
        for (const cust of customers.data) {
          if (cust.id === user.stripeCustomerId) continue; // already checked
          const custSubs = await stripe.subscriptions.list({
            customer: cust.id,
            status: 'all',
            limit: 5,
          });
          const resolved = resolveStatus(custSubs.data, 'free');
          if (resolved.newStatus === 'premium') {
            newStatus = 'premium';
            periodEnd = resolved.periodEnd;
            healedCustomerId = cust.id; // we'll store this as the canonical customer ID
            console.log(`[Stripe] Sync — healed user ${userId}: found active subscription under email-matched customer ${cust.id}`);
            break;
          }
        }
      }

      // Only update if status has actually changed (don't touch beta users)
      if (user.subscriptionStatus !== 'beta' && (user.subscriptionStatus !== newStatus || healedCustomerId)) {
        await db.update(users)
          .set({
            subscriptionStatus: newStatus,
            ...(healedCustomerId ? { stripeCustomerId: healedCustomerId } : {}),
            ...(periodEnd ? { subscriptionCurrentPeriodEnd: periodEnd } : {}),
          })
          .where(eq(users.id, userId));
        console.log(`[Stripe] Sync — user ${userId}: ${user.subscriptionStatus} -> ${newStatus}`);
      }

      const finalStatus = user.subscriptionStatus === 'beta' ? 'beta' : newStatus;
      res.json({ status: finalStatus, isPremium: isPremiumStatus(finalStatus), synced: true });
    } catch (err: any) {
      console.error('[Stripe] Sync error:', err.message);
      res.status(500).json({ message: err.message });
    }
  });

  // ── POST /api/subscription/portal ────────────────────────────────────────
  app.post("/api/subscription/portal", async (req, res) => {
    try {
      const userId = await getUserId(req);
      const [user] = await db.select().from(users).where(eq(users.id, userId));
      if (!user?.stripeCustomerId) {
        return res.status(400).json({ message: "No subscription found" });
      }

      const stripe = await getUncachableStripeClient();
      const host = req.headers.host ?? process.env.REPLIT_DOMAINS?.split(',')[0] ?? 'localhost:5000';
      const protocol = host.startsWith('localhost') ? 'http' : 'https';

      const portalSession = await stripe.billingPortal.sessions.create({
        customer: user.stripeCustomerId,
        return_url: `${protocol}://${host}/`,
      });

      res.json({ url: portalSession.url });
    } catch (err: any) {
      console.error('[Stripe] Portal error:', err);
      res.status(err.status || 500).json({ message: err.message });
    }
  });

  // ── GET /api/subscription/details ────────────────────────────────────────
  // Returns plan type (monthly/annual), period dates, and refund preview for
  // annual subscribers — used by Settings to show cancellation info.
  app.get("/api/subscription/details", async (req, res) => {
    try {
      const userId = await getUserId(req);
      const [user] = await db.select().from(users).where(eq(users.id, userId));
      if (!user?.stripeCustomerId) return res.json({ plan: null, periodStart: null, periodEnd: null, cancelPreview: null });

      const stripe = await getUncachableStripeClient();
      const subs = await stripe.subscriptions.list({ customer: user.stripeCustomerId, status: 'active', limit: 1, expand: ['data.items.data.price'] });
      const sub = subs.data[0];
      if (!sub) return res.json({ plan: null, periodStart: null, periodEnd: null, cancelPreview: null });

      const interval = (sub.items.data[0]?.price as any)?.recurring?.interval ?? 'month';
      const plan = interval === 'year' ? 'annual' : 'monthly';
      const periodStart = new Date(sub.current_period_start * 1000).toISOString();
      const periodEnd = new Date(sub.current_period_end * 1000).toISOString();

      let cancelPreview = null;
      if (plan === 'annual') {
        const { monthsUsed, refundPence, refundFormatted } = calcAnnualRefund(sub.current_period_start * 1000);
        cancelPreview = { monthsUsed, refundPence, refundFormatted, noRefund: refundPence === 0 };
      }

      res.json({ plan, periodStart, periodEnd, cancelPreview });
    } catch (err: any) {
      res.status(err.status || 500).json({ message: err.message });
    }
  });

  // ── POST /api/subscription/cancel ─────────────────────────────────────────
  // Cancels the active subscription immediately.
  // For annual plans: calculates how many full months were used at the monthly
  // rate (£5.99) and refunds the remainder of the £49.99 annual fee.
  // For monthly plans: cancels at period end (no refund — standard Stripe behaviour).
  app.post("/api/subscription/cancel", async (req, res) => {
    try {
      const userId = await getUserId(req);
      const [user] = await db.select().from(users).where(eq(users.id, userId));
      if (!user?.stripeCustomerId) return res.status(400).json({ message: "No subscription found" });

      const stripe = await getUncachableStripeClient();
      const subs = await stripe.subscriptions.list({ customer: user.stripeCustomerId, status: 'active', limit: 1, expand: ['data.items.data.price', 'data.latest_invoice'] });
      const sub = subs.data[0];
      if (!sub) return res.status(400).json({ message: "No active subscription found" });

      const interval = (sub.items.data[0]?.price as any)?.recurring?.interval ?? 'month';
      const isAnnual = interval === 'year';

      let refundIssued: { pence: number; formatted: string } | null = null;

      if (isAnnual) {
        const { monthsUsed, refundPence, refundFormatted } = calcAnnualRefund(sub.current_period_start * 1000);
        console.log(`[Cancel] annual sub userId=${userId} monthsUsed=${monthsUsed} refund=${refundFormatted}`);

        // Cancel immediately
        await stripe.subscriptions.cancel(sub.id);

        // Issue partial refund if any amount is due
        if (refundPence > 0) {
          const invoice = sub.latest_invoice as import('stripe').default.Invoice | null;
          const paymentIntentId = typeof invoice?.payment_intent === 'string'
            ? invoice.payment_intent
            : (invoice?.payment_intent as any)?.id;

          if (paymentIntentId) {
            await stripe.refunds.create({ payment_intent: paymentIntentId, amount: refundPence });
            console.log(`[Cancel] refund issued ${refundFormatted} via payment_intent ${paymentIntentId}`);
            refundIssued = { pence: refundPence, formatted: refundFormatted };
          } else {
            console.warn(`[Cancel] no payment_intent on invoice — refund skipped`);
          }
        }
      } else {
        // Monthly: cancel at period end
        await stripe.subscriptions.update(sub.id, { cancel_at_period_end: true });
      }

      // Update DB
      await db.update(users).set({ subscriptionStatus: 'free' }).where(eq(users.id, userId));

      res.json({ ok: true, isAnnual, refundIssued });
    } catch (err: any) {
      console.error('[Cancel] error:', err);
      res.status(err.status || 500).json({ message: err.message });
    }
  });

  // ── POST /api/admin/grant-beta ────────────────────────────────────────────
  // Allows granting or revoking beta (free premium) access for any user.
  // Protected by ADMIN_CODE env var.
  app.post("/api/admin/grant-beta", async (req, res) => {
    try {
      const { username, grant, adminCode } = req.body;
      const expectedCode = process.env.ADMIN_CODE;

      if (!expectedCode || adminCode !== expectedCode) {
        return res.status(403).json({ message: "Invalid admin code" });
      }
      if (!username) {
        return res.status(400).json({ message: "username required" });
      }

      const newStatus = grant !== false ? 'beta' : 'free';
      const result = await db.update(users)
        .set({ subscriptionStatus: newStatus })
        .where(eq(users.username, username))
        .returning({ id: users.id, username: users.username, subscriptionStatus: users.subscriptionStatus });

      if (!result.length) {
        return res.status(404).json({ message: "User not found" });
      }

      res.json({ message: `User ${username} subscription set to '${newStatus}'`, user: result[0] });
    } catch (err: any) {
      res.status(500).json({ message: err.message });
    }
  });

  // ── GET /api/admin/users ──────────────────────────────────────────────────
  app.get("/api/admin/users", async (req, res) => {
    try {
      const { adminCode } = req.query as any;
      const expectedCode = process.env.ADMIN_CODE;
      if (!expectedCode || adminCode !== expectedCode) {
        return res.status(403).json({ message: "Invalid admin code" });
      }

      const allUsers = await db.select({
        id: users.id,
        username: users.username,
        displayName: users.displayName,
        subscriptionStatus: users.subscriptionStatus,
        stripeCustomerId: users.stripeCustomerId,
      }).from(users).orderBy(users.id);

      res.json(allUsers);
    } catch (err: any) {
      res.status(500).json({ message: err.message });
    }
  });
}
